version: "3"

services:
  nextjs:
    image: "frontend-${TAG}"
    ports:
      - 3000:3000
    build:
      context: ../CT-Logging-System
      dockerfile: Dockerfile
    volumes:
      - ../excel-ct:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env.production