const INITIAL_FORM_STATE = {
  PID: "",
  inPatient: false,
  age: "",
  weight: "",
  height: "",
  circumference: "",
  date: "",
  urgent: false,
  sedation: false,
  protocol: [],
  kV_A: "",
  kV_B: "",
  pitch: "",
  injectionSite: "",
  handInjection: false,
  mixedContrast: false,
  type: "",
  rate: "",
  volume: "",
  directPostContrast: false,
  ttp: "",
  delay1: "",
  delay2: "",
  delay3: "",
  delay4: "",
  radiographers: "",
  radiologists: "",
  nurses: "",
  keywords: "",
  remark: "",
};

export default INITIAL_FORM_STATE;
