const INITIAL_FORM_STATE = {
  PID: "Y1234",
  inPatient: false,
  age: "1",
  weight: 1,
  height: 1,
  circumference: null,
  Date: null,
  urgent: false,
  sedation: false,
  protocol: [],
  kV_a: "70",
  kV_b: null,
  pitch: 1,
  injectionSite: null,
  handInjection: null,
  mixedContrast: null,
  contrastType: null,
  rate: null,
  volume: null,
  directPostContrast: false,
  ttp: null,
  radiographers: [],
  radiologists: [],
  nurses: [],
  keywords: null,
  remark: null,
  delays: null,
};

export default INITIAL_FORM_STATE;
