const INITIAL_FORM_STATE = {
  PID: "",
  name: "",
  date: new Date(),
  radiologistInCharge: [],
  sedation: "",
  breathingControl: "",
  IVSite: [{ location: [], side: [], Diffusics: false }],
  targetHR: "",
  scanMode: {
    HRDependent: false,
    flash: { mode: "", trigger: "" },
    ss: { status: false, range: [0, 0] },
    monitoringMethod: "",
    ROI: "",
  },
  phase: [
    {
      name: "Plain",
      scanRange: "",
      processing: { caScore: false },
      remark: "",
    },
    { name: [], scanRange: "", processing: [], remark: "" },
    { name: [], scanRange: "", processing: [], remark: "" },
    { name: [], scanRange: "", processing: [], remark: "" },
  ],
  readyForRecord: false,
  protocol: [],
  contrastRegime: "",
  studyDose: "",
  seriesDose: "",
  seriesCTDI: "",
  heartRate: { min: "", max: "", average: "", variance: "" },
  scanTechnique: "",
  breathingControl_record: "",
  depictionOfROI: "",
  satisfaction: null,
  artefact: "",
  remarks: "",
  delays: [""],
};

export default INITIAL_FORM_STATE;
